### ISSUE TITLE
Update admin_html_head.php to allow inline CSS additions

### ISSUE THREAD

**Issue by lat9** [zencart/zc-v1-series#544]
In the current implementation of the standardized admin HTML header, there's a provision for a page script to identify additional CSS **files** to load, but there's not a way for a page to specify in-line CSS additions.

My preference, FWIW, for the admin-level plugins I've created, is to include both the additional CSS and javascript **in-line** to reduce the number of files shipped for the plugin and to keep the CSS/JS/PHP files closely coupled.  It would take a small addition in the admin_html_head.php file to define another global variable which, if set, contains the CSS to be in-lined.

**Comment by DivaVocals** [comment]
Would this be similar to how you added Font Awesome to the CSS buttons module???

**Comment by lat9** [comment]
Nope, it's based on the ZC 1.6.0 admin restructuring.  The new, common, header processing provides for an add-on admin page to specify a css **file** that should be loaded, but doesn't make the provision for the specification of in-line CSS.

**Comment by jtwebsitedesign** [comment]
Hmm, just my two cents, but it is probably better to keep CSS in a separate file for easier maintenance/upgrades. By in-line, do you mean style="" inserted throughout the file, or <style></style> tags in the header?

**Comment by lat9** [comment]
@jtwebsitedesign, that's true for the "base", out-of-the-box, Zen Cart styling, but I'm more focused (with this issue) on support for admin-level plugins.  Like I said above, it's my personal preference (for the admin-level plugins I develop) to keep the **additional** styling used by that plugin as part of the plugin's base code.

That way, there's one less file to install for the plugin and it helps (me, anyway) to more easily keep the changes (both PHP and CSS) synchronized.

**Comment by jtwebsitedesign** [comment]
That's true that there would be one less file for the plugin, but I'm looking at it from a store manager's perspective when upgrading the cart. When core files are overwritten, the less inline code that is changed in that core file, the better.

It's helpful for any code changes to be a large chunk of commented code like <! -- start [module name] here -- >, rather than inline CSS sprinkled throughout the file. I mentioned above (but looks like the code was filtered out) that using the <-style-> tag in the header would be totally fine, it's just the inline style="" that I'm more worried about.

Again, I'm just putting my two cents and giving another perspective. Feel free to move forward how you think is best.

**Comment by lat9** [comment]
Jackie, my focus is on separately-developed admin plugins.  The "issue" is that, in the updated ZC 1.6.0 environment, that **all** the admin header-processing (the head tag) happens when the "page" issues a:

require('includes/admin_html_head.php');

It's the processing in that module that I'm requesting be changed so that additional CSS, which I called in-line but I meant as in-lined into a &lt;style&gt; tag, can be specified.

I agree with you on core-file changes in general, but the judicious use of comments blocking the changes certainly helps.

**Comment by drbyte** [comment]
@lat9 I'm wondering if this fact helps solve your problem ...

The `require('includes/admin_html_head.php');` *opens* the `<head>` tag, but does *not* close it. 
You can easily insert your own `<style>...</style>` code immediately after the require, or at least sometime before the closing `</head>` tag a couple lines later. 

Would that accommodate what you're after? It certainly means you wouldn't need to distribute a .css file with the plugin if your styling is relatively brief.

**Comment by lat9** [comment]
Sure it could; I was under the impression that the &lt;style&gt; tags, for valid HTML, needed to be before the &lt;script&gt; tags.  If that's not true, then the mechanism you indicated (inserting any CSS styling prior to adding the closing-head-tag) works just fine.

**Comment by drbyte** [comment]
I'm pretty sure it's not necessary for "valid HTML".

But, some purists will say you should put `<style>` content before `<script>` just so that you don't get a "flash of unstyled text" while waiting for the `<script>` stuff to load. 

Unless you're dealing with a bunch of extremely elaborate inline styling I don't think it's going to matter. And if you do need complicated styling, then a .css file will mitigate that. 

*(And for those who say loading lots of .css files is a problem, I recommend reading up on HTTP/2 since it will make combining/minification and sharding moot.)*

**Comment by jtwebsitedesign** [comment]
Thanks for clarifying @lat9, sounds like we're both on the same page. Sorry for complicating things :/

**Comment by drbyte** [comment]
This was good discussion. I'm closing it because I believe we determined that there is not currently any need to change core code at this time. 

Happy to reconsider if a specific scenario is presented to clearly explain otherwise ;)
