### ISSUE TITLE
Remove closing php tags for edited files

### ISSUE THREAD

**Issue by mc12345678** [zencart/zc-v1-series#836]
Didn't find an associated issue so created one.  As part of other code changes being made, I am trying to address the files in whole rather than just the one part that initiated a change to the file.  As part of that and previously stated goals in the forum, this issue is to "track" the removal of the closing tag of affected files.

**Comment by drbyte** [comment]
> I am trying to address the files in whole rather than just the one part that initiated a change to the file.

Fair, but do keep in mind that commits (and ideally Pull Requests too) should be atomic with respect to a specific change being implemented. This is primarily so that one can look back at PRs to understand specifically what was changed and why. When a file is refactored in numerous ways in one PR then that destroys the ability to follow the bouncing ball.

**Comment by drbyte** [comment]
Not sure this needs to be an issue ticket here.
