### ISSUE TITLE
Suggestion: Checkbox on Admin Users screen "use as Master Password" 

### ISSUE THREAD

**Issue by scottcwilson** [zencart/zc-v1-series#918]
This way, accounts which are so checked could be used for catalog side logins for any registered user.

If approved, I will do for 1.6.0.

**Comment by drbyte** [comment]
Wouldn’t it make more sense for a plugin to handle its own requirements?

Suggestion:
a) Add “Master Password” as an Admin Profile checkbox, instead of beside every “user”.
b) Then the plugin should check for any password that matches against an Admin user with that profile permission and whose password has not expired or been locked out.

**Comment by scottcwilson** [comment]
This was to build the functionality in so a plugin would not be needed.  If you don't like the idea, I can close - just a thought.

**Comment by drbyte** [comment]
If the plugin adds a profile entry to the database profile permissions table, then the code should just automatically update the admin UI. So no core code changes would be needed.

**Comment by scottcwilson** [comment]
Didn't think of that implementation path - nice!  OK I will use that approach.

**Comment by scottcwilson** [comment]
Let's close this issue.  When we start making mods for 1.6.0, I will follow your direction.  Thanks for the idea!
